/**
 * PACT Phase 6A: Command Center Registry
 * Authoritative registry of standard navigation, quick action, and settings commands.
 */

import { CommandItem } from './types';

export const STATIC_QUICK_ACTIONS: CommandItem[] = [
  {
    id: 'action-create-task',
    title: 'Create Task',
    subtitle: 'Add a new deadline commitment with optional consequence',
    category: 'quick_action',
    keywords: ['new task', 'add task', 'todo', 'deadline', 'commitment', 'pact'],
    iconName: 'CheckSquare',
    shortcut: 'C T',
    actionKey: 'create_task',
  },
  {
    id: 'action-create-goal',
    title: 'Create Goal',
    subtitle: 'Define a high-level strategic objective',
    category: 'quick_action',
    keywords: ['new goal', 'add goal', 'objective', 'milestone', 'vision', 'aim'],
    iconName: 'Target',
    shortcut: 'C G',
    actionKey: 'create_goal',
  },
  {
    id: 'action-create-project',
    title: 'Create Project',
    subtitle: 'Start a focused initiative attached to a goal',
    category: 'quick_action',
    keywords: ['new project', 'add project', 'initiative', 'folder', 'deliverable'],
    iconName: 'FolderKanban',
    shortcut: 'C P',
    actionKey: 'create_project',
  },
  {
    id: 'action-start-focus',
    title: 'Start Focus Session',
    subtitle: 'Launch deep work countdown or stopwatch',
    category: 'quick_action',
    keywords: ['focus', 'pomodoro', 'timer', 'deep work', 'stopwatch', 'session', 'pact timer'],
    iconName: 'Timer',
    shortcut: 'S F',
    href: '/app/focus',
    actionKey: 'navigate',
  },
  {
    id: 'action-log-expense',
    title: 'Log Expense',
    subtitle: 'Record an outgoing financial transaction',
    category: 'quick_action',
    keywords: ['expense', 'spend', 'money', 'cost', 'payment', 'purchase', 'outflow'],
    iconName: 'ArrowDownRight',
    shortcut: 'L E',
    actionKey: 'log_expense',
  },
  {
    id: 'action-log-income',
    title: 'Log Income',
    subtitle: 'Record an incoming revenue or salary item',
    category: 'quick_action',
    keywords: ['income', 'salary', 'deposit', 'earn', 'revenue', 'inflow'],
    iconName: 'ArrowUpRight',
    shortcut: 'L I',
    actionKey: 'log_income',
  },
];

export const STATIC_NAVIGATION_COMMANDS: CommandItem[] = [
  {
    id: 'nav-overview',
    title: 'Go to Overview',
    subtitle: 'Command dashboard and daily active focus',
    category: 'navigation',
    keywords: ['home', 'dashboard', 'overview', 'summary', 'today'],
    iconName: 'LayoutDashboard',
    href: '/app',
    actionKey: 'navigate',
  },
  {
    id: 'nav-focus',
    title: 'Go to Focus Timer',
    subtitle: 'Deep work sessions, active timer, and focus analytics',
    category: 'navigation',
    keywords: ['focus', 'timer', 'deep work', 'session', 'pomodoro', 'stopwatch', 'stats'],
    iconName: 'Timer',
    href: '/app/focus',
    actionKey: 'navigate',
  },
  {
    id: 'nav-planner',
    title: 'Go to Planner',
    subtitle: 'Day, week, and time-block schedule planner',
    category: 'navigation',
    keywords: ['planner', 'schedule', 'timeblock', 'agenda', 'calendar'],
    iconName: 'Calendar',
    href: '/app/planner',
    actionKey: 'navigate',
  },
  {
    id: 'nav-tasks',
    title: 'Go to Tasks',
    subtitle: 'Manage task commitments, filters, and statuses',
    category: 'navigation',
    keywords: ['tasks', 'todos', 'backlog', 'commitments', 'deadlines'],
    iconName: 'CheckSquare',
    href: '/app/tasks',
    actionKey: 'navigate',
  },
  {
    id: 'nav-goals',
    title: 'Go to Goals',
    subtitle: 'Review strategic milestones and progress',
    category: 'navigation',
    keywords: ['goals', 'objectives', 'strategy', 'targets'],
    iconName: 'Target',
    href: '/app/goals',
    actionKey: 'navigate',
  },
  {
    id: 'nav-projects',
    title: 'Go to Projects',
    subtitle: 'Kanban boards and scoped initiatives',
    category: 'navigation',
    keywords: ['projects', 'initiatives', 'kanban', 'boards'],
    iconName: 'FolderKanban',
    href: '/app/projects',
    actionKey: 'navigate',
  },
  {
    id: 'nav-finance',
    title: 'Go to Finance',
    subtitle: 'Transactions ledger, subscriptions, and budgets',
    category: 'navigation',
    keywords: ['finance', 'money', 'budget', 'subscriptions', 'recurring', 'ledger'],
    iconName: 'Wallet',
    href: '/app/finance',
    actionKey: 'navigate',
  },
  {
    id: 'nav-analytics',
    title: 'Go to Analytics',
    subtitle: 'Follow-through scoring, velocity, and trends',
    category: 'navigation',
    keywords: ['analytics', 'metrics', 'stats', 'velocity', 'follow through', 'charts'],
    iconName: 'TrendingUp',
    href: '/app/analytics',
    actionKey: 'navigate',
  },
  {
    id: 'nav-accountability',
    title: 'Go to Accountability',
    subtitle: 'Consequence matrix, emergency waivers, and history',
    category: 'navigation',
    keywords: ['accountability', 'consequences', 'waiver', 'penalties', 'proof', 'history'],
    iconName: 'ShieldAlert',
    href: '/app/accountability',
    actionKey: 'navigate',
  },
  {
    id: 'nav-settings',
    title: 'Go to Settings',
    subtitle: 'Account profile, notification channels, data export',
    category: 'settings',
    keywords: ['settings', 'preferences', 'profile', 'export', 'google calendar', 'privacy'],
    iconName: 'Settings',
    href: '/app/settings',
    actionKey: 'navigate',
  },
];

export const ALL_STATIC_COMMANDS: CommandItem[] = [
  ...STATIC_QUICK_ACTIONS,
  ...STATIC_NAVIGATION_COMMANDS,
];
