'use server';

/**
 * PACT Phase 13: Multi-Device Sync & Delta Replication Server Actions
 * Server-authoritative delta ingestion, deduplication, cursor management, and cross-device fan-out.
 */

import { createClient } from '@/lib/supabase/server';
import {
  DeltaSyncBatchRequest,
  DeltaSyncBatchResponse,
  SyncDelta,
  isSafeReplicationType,
  sanitizeDeltaPayload,
} from '@/lib/offline/delta-engine';
import { StagedProofAttachment } from '@/lib/offline/attachment-cache';

export interface DeviceRegistryEntry {
  id: string;
  deviceName: string;
  clientType: string;
  lastSeenAt: string;
  syncCursor: string;
  createdAt: string;
}

/**
 * Replicates a batch of client deltas and retrieves newer remote deltas since the given cursor.
 */
export async function replicateDeltasAction(
  batch: DeltaSyncBatchRequest
): Promise<DeltaSyncBatchResponse> {
  const supabase = await createClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  const serverTimestamp = new Date().toISOString();

  if (authError || !user) {
    return {
      success: false,
      newCursor: batch.sinceCursor || serverTimestamp,
      appliedOpIds: [],
      rejectedOpIds: batch.deltas.map((d) => ({ opId: d.opId, reason: 'UNAUTHORIZED' })),
      serverDeltas: [],
      conflictsResolved: 0,
      serverTimestamp,
    };
  }

  // 1. Register or update device record in device_registry
  try {
    await supabase.from('device_registry').upsert(
      {
        id: batch.deviceId,
        user_id: user.id,
        device_name: batch.deviceName || 'Web Client',
        client_type: batch.clientType || 'web_desktop',
        last_seen_at: serverTimestamp,
        sync_cursor: serverTimestamp,
      },
      { onConflict: 'id' }
    );
  } catch {
    // Non-fatal device registry error
  }

  const appliedOpIds: string[] = [];
  const rejectedOpIds: Array<{ opId: string; reason: string }> = [];

  // 2. Validate and ingest incoming client deltas
  for (const delta of batch.deltas) {
    if (!isSafeReplicationType(delta.entityType)) {
      rejectedOpIds.push({
        opId: delta.opId,
        reason: `REJECTED_SERVER_AUTHORITATIVE: Entity type '${delta.entityType}' cannot be modified via client delta sync.`,
      });
      continue;
    }

    try {
      const sanitizedPayload = delta.action === 'DELETE' ? {} : sanitizeDeltaPayload(delta.payload);

      const { error: insertError } = await supabase.from('sync_delta_logs').insert({
        id: delta.opId,
        user_id: user.id,
        device_id: batch.deviceId,
        entity_type: delta.entityType,
        entity_id: delta.entityId,
        action: delta.action,
        delta: sanitizedPayload,
        version: delta.version,
        logical_clock: delta.logicalClock,
        client_timestamp: delta.clientTimestamp,
        server_timestamp: serverTimestamp,
      });

      if (insertError) {
        if (insertError.code === '23505') {
          // Idempotent duplicate: already processed
          appliedOpIds.push(delta.opId);
        } else {
          rejectedOpIds.push({ opId: delta.opId, reason: insertError.message });
        }
      } else {
        appliedOpIds.push(delta.opId);
      }
    } catch (err) {
      rejectedOpIds.push({
        opId: delta.opId,
        reason: err instanceof Error ? err.message : 'Database insertion error',
      });
    }
  }

  // 3. Fetch newer server deltas generated by other devices since client's cursor
  let serverDeltas: SyncDelta[] = [];
  try {
    let query = supabase
      .from('sync_delta_logs')
      .select('*')
      .eq('user_id', user.id)
      .neq('device_id', batch.deviceId)
      .order('server_timestamp', { ascending: true })
      .limit(100);

    if (batch.sinceCursor) {
      query = query.gt('server_timestamp', batch.sinceCursor);
    }

    const { data: logs } = await query;

    if (logs && Array.isArray(logs)) {
      serverDeltas = logs.map((log) => ({
        opId: log.id,
        deviceId: log.device_id,
        entityType: log.entity_type,
        entityId: log.entity_id,
        action: log.action as 'UPSERT' | 'DELETE',
        version: log.version,
        logicalClock: Number(log.logical_clock),
        clientTimestamp: log.client_timestamp,
        payload: log.delta || {},
        tombstone: log.action === 'DELETE',
      }));
    }
  } catch {
    // Non-fatal query fallback
  }

  return {
    success: true,
    newCursor: serverTimestamp,
    appliedOpIds,
    rejectedOpIds,
    serverDeltas,
    conflictsResolved: 0,
    serverTimestamp,
  };
}

/**
 * Lists all registered devices for the current authenticated user.
 */
export async function fetchRegisteredDevicesAction(): Promise<{
  success: boolean;
  data?: DeviceRegistryEntry[];
  error?: string;
}> {
  const supabase = await createClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Unauthorized' };
  }

  const { data, error } = await supabase
    .from('device_registry')
    .select('id, device_name, client_type, last_seen_at, sync_cursor, created_at')
    .eq('user_id', user.id)
    .order('last_seen_at', { ascending: false });

  if (error) {
    return { success: false, error: error.message };
  }

  return {
    success: true,
    data: (data || []).map((d) => ({
      id: d.id,
      deviceName: d.device_name,
      clientType: d.client_type,
      lastSeenAt: d.last_seen_at,
      syncCursor: d.sync_cursor,
      createdAt: d.created_at,
    })),
  };
}

/**
 * Unregisters / revokes a remote device.
 */
export async function unregisterDeviceAction(deviceId: string): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Unauthorized' };
  }

  const { error } = await supabase
    .from('device_registry')
    .delete()
    .eq('id', deviceId)
    .eq('user_id', user.id);

  if (error) {
    return { success: false, error: error.message };
  }

  return { success: true };
}

/**
 * Uploads staged offline proof metadata to server repository.
 */
export async function uploadStagedProofAttachmentAction(
  attachment: StagedProofAttachment
): Promise<{ success: boolean; remotePath?: string; error?: string }> {
  const supabase = await createClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return { success: false, error: 'Unauthorized' };
  }

  const remotePath = `proofs/${user.id}/${attachment.commitmentId}/${attachment.id}_${attachment.fileName}`;

  const { error } = await supabase.from('staged_proof_attachments').insert({
    id: attachment.id,
    user_id: user.id,
    commitment_id: attachment.commitmentId,
    file_name: attachment.fileName,
    mime_type: attachment.mimeType,
    file_size_bytes: attachment.fileSizeBytes,
    sha256_hash: attachment.sha256Hash,
    storage_path: remotePath,
    status: 'UPLOADED',
  });

  if (error) {
    return { success: false, error: error.message };
  }

  return { success: true, remotePath };
}
